  dotnet restore "./01 - Demo 1 - Delayed/Delayed.Tests/Delayed.Tests.csproj"
  dotnet test "./01 - Demo 1 - Delayed/Delayed.Tests/Delayed.Tests.csproj"
  dotnet restore "./02 - Lab 1 - SpaceBook/SpaceBook.Tests/SpaceBook.Tests.csproj"
  dotnet test "./02 - Lab 1 - SpaceBook/SpaceBook.Tests/SpaceBook.Tests.csproj"
  dotnet restore "./03 - Lab 2 - Bugfix Dracula/VampireSlayer.Tests/VampireSlayer.Tests.csproj"
  dotnet test "./03 - Lab 2 - Bugfix Dracula/VampireSlayer.Tests/VampireSlayer.Tests.csproj"
  dotnet restore "./04 - Demo 2 - Greeting/Greeting.Tests/Greeting.Tests.csproj"
  dotnet test "./04 - Demo 2 - Greeting/Greeting.Tests/Greeting.Tests.csproj"
  dotnet restore "./05 - Lab 3 - PetShop/PetShop.Tests/PetShop.Tests.csproj"
  dotnet test "./05 - Lab 3 - PetShop/PetShop.Tests/PetShop.Tests.csproj"
  dotnet restore "./06 - Lab 4 - Flight/Flight.Tests/Flight.Tests.csproj"
  dotnet test "./06 - Lab 4 - Flight/Flight.Tests/Flight.Tests.csproj"
  dotnet restore "./07 - Demo 3 - Refactoring/Refactoring.Tests/Refactoring.Tests.csproj"
  dotnet test "./07 - Demo 3 - Refactoring/Refactoring.Tests/Refactoring.Tests.csproj"
  dotnet restore "./08 - Lab 5 - MovieRental/MovieRental.Tests/MovieRental.Tests.csproj"
  dotnet test "./08 - Lab 5 - MovieRental/MovieRental.Tests/MovieRental.Tests.csproj"
